# Generated by Django 5.2.6 on 2025-10-06 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPaymentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_payments", models.IntegerField(default=0)),
                ("verified_payments", models.IntegerField(default=0)),
                ("pending_payments", models.IntegerField(default=0)),
                ("failed_payments", models.IntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "verified_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pending_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "medicine_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "lab_test_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "appointment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "online_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cod_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cash_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "daily_payment_summary",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=100, unique=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("medicine", "Medicine Order"),
                            ("lab_test", "Lab Test"),
                            ("appointment", "Doctor Appointment"),
                            ("consultation", "Doctor Consultation"),
                            ("home_collection", "Home Sample Collection"),
                            ("other", "Other Services"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("online", "Online Payment (Razorpay)"),
                            ("cod", "Cash on Delivery"),
                            ("cash", "Direct Cash"),
                            ("card", "Card Payment"),
                            ("upi", "UPI Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Payment Pending"),
                            ("received", "Payment Received"),
                            ("verified", "Payment Verified by Admin"),
                            ("failed", "Payment Failed"),
                            ("refunded", "Payment Refunded"),
                            ("disputed", "Payment Disputed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_admin_verified", models.BooleanField(default=False)),
                (
                    "admin_verification_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("razorpay_response", models.JSONField(blank=True, null=True)),
                ("order_reference", models.CharField(max_length=100)),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_phone", models.CharField(max_length=15)),
                ("customer_address", models.TextField(blank=True)),
                ("payment_initiated_at", models.DateTimeField(auto_now_add=True)),
                ("payment_received_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin verification notes and comments"
                    ),
                ),
                (
                    "admin_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_taken", models.CharField(max_length=50)),
                ("previous_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment_management.paymentrecord",
                    ),
                ),
            ],
            options={
                "db_table": "payment_verification_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
