# Generated by Django 5.2.6 on 2025-09-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0007_remove_stocktransaction_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
