# Generated by Django 5.2.6 on 2025-10-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0009_add_delivery_and_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="composition",
            field=models.TextField(
                blank=True,
                help_text="Active ingredients and their quantities",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="hsn_code",
            field=models.CharField(
                blank=True,
                help_text="HSN code for tax classification",
                max_length=20,
                null=True,
            ),
        ),
    ]
