# Generated by Django 5.2.6 on 2025-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0010_medicine_composition_medicine_hsn_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
