# Generated by Django 5.2.4 on 2025-10-04 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0006_alter_user_username"),
        ("pharmacy", "0011_alter_medicine_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionUpload",
            fields=[
                ("upload_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "prescription_image",
                    models.ImageField(
                        help_text="Upload clear image of your prescription",
                        upload_to="prescriptions/%Y/%m/%d/",
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(
                        blank=True,
                        help_text="Doctor's name from prescription",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "prescription_date",
                    models.DateField(
                        blank=True, help_text="Date on the prescription", null=True
                    ),
                ),
                (
                    "patient_notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional notes or specific requirements",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed by Pharmacist"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("fulfilled", "Order Fulfilled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "pharmacist_notes",
                    models.TextField(
                        blank=True,
                        help_text="Pharmacist's notes and recommendations",
                        null=True,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup at Pharmacy"),
                            ("delivery", "Home Delivery"),
                        ],
                        default="pickup",
                        max_length=20,
                    ),
                ),
                ("delivery_address", models.TextField(blank=True, null=True)),
                (
                    "delivery_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_uploads",
                        to="hospital.patient",
                    ),
                ),
                (
                    "pharmacist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_prescriptions",
                        to="pharmacy.pharmacist",
                    ),
                ),
                (
                    "related_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescription_upload",
                        to="pharmacy.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "dosage",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 1 tablet twice daily",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "days",
                    models.IntegerField(
                        blank=True, help_text="Number of days", null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.medicine",
                    ),
                ),
                (
                    "prescription_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="pharmacy.prescriptionupload",
                    ),
                ),
            ],
        ),
    ]
