# Generated by Django 5.2.4 on 2025-10-05 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0048_prescription_test_assigned_technician_and_more"),
        ("pharmacy", "0012_prescriptionupload_prescriptionmedicine"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionupload",
            name="doctor_prescription",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to doctor's digital prescription if available",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pharmacy_uploads",
                to="doctor.prescription",
            ),
        ),
    ]
