# Generated by Django 5.2.6 on 2025-10-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0013_prescriptionupload_doctor_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptionupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("reviewed", "Reviewed by Pharmacist"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("paid_pending", "Payment Received - Processing"),
                    ("fulfilled", "Order Fulfilled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
