# Generated by Django 5.2.6 on 2025-10-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0014_alter_prescriptionupload_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="batch_no",
            field=models.CharField(
                blank=True,
                help_text="Manufacturing batch number",
                max_length=100,
                null=True,
            ),
        ),
    ]
