# Generated by Django 5.2.4 on 2025-09-19 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0045_report_report_pdf_report_uploaded_at"),
        ("hospital", "0004_alter_user_login_status"),
        ("pharmacy", "0008_medicine_expiry_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayPayment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("razorpay_order_id", models.CharField(max_length=255, unique=True)),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("pharmacy", "Pharmacy"),
                            ("test", "Test"),
                            ("prescription", "Prescription"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.JSONField(blank=True, null=True)),
                ("receipt", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctor.appointment",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacy.order",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctor.prescription",
                    ),
                ),
                (
                    "test_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctor.testorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
