# Generated by Django 5.2.4 on 2025-09-19 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("razorpay_payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="paid",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_email", models.CharField(max_length=255)),
                ("customer_phone", models.CharField(max_length=20)),
                ("customer_address", models.TextField(blank=True, null=True)),
                (
                    "company_name",
                    models.CharField(default="M/S MAHIMA MEDICARE", max_length=255),
                ),
                (
                    "company_address",
                    models.TextField(default="ORTI, BAGHUNI, NEMALA, CUTTACK"),
                ),
                (
                    "company_phone",
                    models.CharField(default="9348221721", max_length=20),
                ),
                (
                    "license_no",
                    models.CharField(
                        default="CU-VI46219/R, 42220/RC, 20123RX", max_length=100
                    ),
                ),
                ("gstin", models.CharField(default="21AXRPN9340C1ZH", max_length=20)),
                ("state_code", models.CharField(default="21", max_length=5)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "terms_conditions",
                    models.TextField(
                        blank=True,
                        default="Payment is due within 30 days. Thank you for your business!",
                        null=True,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="razorpay_payment.razorpaypayment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("item_type", models.CharField(blank=True, max_length=50, null=True)),
                ("item_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="razorpay_payment.invoice",
                    ),
                ),
            ],
        ),
    ]
