# Generated by Django 5.2.4 on 2025-10-04 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0012_prescriptionupload_prescriptionmedicine"),
        ("razorpay_payment", "0002_invoice_invoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="razorpaypayment",
            name="prescription_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pharmacy.prescriptionupload",
            ),
        ),
        migrations.AlterField(
            model_name="razorpaypayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("appointment", "Appointment"),
                    ("pharmacy", "Pharmacy"),
                    ("test", "Test"),
                    ("prescription", "Prescription"),
                    ("prescription_order", "Prescription Order"),
                ],
                max_length=20,
            ),
        ),
    ]
