# Generated by Django 5.2.6 on 2025-10-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("razorpay_payment", "0003_razorpaypayment_prescription_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="company_email",
            field=models.CharField(
                default="mahimamedicare01@gmail.com", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company_address",
            field=models.TextField(
                default="ଆପଣଙ୍କ ସ୍ବାସ୍ଥ୍ୟ ର ସାଥୀ (Your Health Partner)\nBarkoliya Bajar, Orti, Cuttack, 754209\nWeb: mahimamedicare.co.in"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company_name",
            field=models.CharField(default="MAHIMA MEDICARE", max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company_phone",
            field=models.CharField(default="+91 8763814619", max_length=20),
        ),
    ]
