# Generated by Django 5.2.6 on 2025-10-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0004_alter_user_login_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="prescription_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload prescription image for pharmacist",
                null=True,
                upload_to="prescriptions/",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="prescription_notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about prescription", null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="prescription_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
