# Generated by Django 5.2.6 on 2025-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_patient_prescription_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Username can contain spaces and most characters",
                max_length=150,
                unique=True,
            ),
        ),
    ]
