# Generated by Django 5.2.6 on 2025-09-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0044_appointment_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_pdf",
            field=models.FileField(blank=True, null=True, upload_to="lab_reports/"),
        ),
        migrations.AddField(
            model_name="report",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
