# Generated by Django 5.2.4 on 2025-09-19 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0045_report_report_pdf_report_uploaded_at"),
        ("hospital_admin", "0005_admin_information_hospital"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="report",
            name="assigned_technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_reports",
                to="hospital_admin.clinical_laboratory_technician",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="doctor_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="lab_notes",
            field=models.TextField(
                blank=True, help_text="Internal lab notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="patient_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="priority",
            field=models.CharField(
                choices=[("normal", "Normal"), ("urgent", "Urgent"), ("stat", "STAT")],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Collection"),
                    ("collected", "Sample Collected"),
                    ("processing", "Under Processing"),
                    ("completed", "Report Ready"),
                    ("delivered", "Report Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="technician_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="test_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctor.testorder",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="collection_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="other_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="receiving_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="result",
            field=models.TextField(blank=True, null=True),
        ),
    ]
