# Generated by Django 5.2.4 on 2025-09-21 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0046_alter_report_options_report_assigned_technician_and_more"),
        ("hospital", "0004_alter_user_login_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor_review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="doctor_review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor_review",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doctor_review",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
            ),
        ),
        migrations.AlterField(
            model_name="doctor_review",
            name="message",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="doctor_review",
            unique_together={("doctor", "patient")},
        ),
    ]
