# Generated by Django 5.2.4 on 2025-09-21 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "doctor",
            "0047_alter_doctor_review_options_doctor_review_created_at_and_more",
        ),
        ("hospital_admin", "0005_admin_information_hospital"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription_test",
            name="assigned_technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tests",
                to="hospital_admin.clinical_laboratory_technician",
            ),
        ),
        migrations.AddField(
            model_name="prescription_test",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription_test",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescription_test",
            name="test_status",
            field=models.CharField(
                choices=[
                    ("prescribed", "Prescribed"),
                    ("paid", "Payment Completed"),
                    ("collected", "Sample Collected"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("delivered", "Report Delivered"),
                ],
                default="prescribed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prescription_test",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="prescription_test",
            name="test_info_pay_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("partial", "Partial"),
                    ("refunded", "Refunded"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
