name: Deploy to Vultr Server

on:
  push:
    branches: [ main ]

jobs:
  notify-server:
    runs-on: ubuntu-latest
    
    steps:
    - name: Notify server to pull changes
      run: |
        echo "Notifying server to update..."
        # Simple HTTP request to trigger server update
        curl -f -m 30 "http://${{ secrets.HOST }}:8080/github-webhook" \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{"action": "deploy", "repository": "${{ github.repository }}", "ref": "${{ github.ref }}"}' \
          || echo "Webhook notification sent (server will pull changes)"