name: Deploy to Vultr Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        timeout: 60s
        script: |
          echo "Starting deployment..."
          cd /var/www/mahima-medicare || exit 1
          
          echo "Pulling latest changes..."
          git pull origin main || exit 1
          
          echo "Activating virtual environment..."
          source venv/bin/activate || exit 1
          
          echo "Installing dependencies..."
          pip install -r requirements.txt
          
          echo "Running migrations..."
          python manage.py migrate --noinput
          
          echo "Collecting static files..."
          python manage.py collectstatic --noinput
          
          echo "Restarting application..."
          pkill -f gunicorn || true
          sleep 2
          
          echo "Starting Gunicorn..."
          nohup gunicorn --config gunicorn.conf.py healthstack.wsgi:application > /dev/null 2>&1 &
          
          echo "Deployment completed!"
          sleep 3
          ps aux | grep gunicorn | grep -v grep